### ISSUE TITLE
howto tutorial

### ISSUE THREAD

**Issue by hadifarnoud** [DNSCrypt/doh-server#68]
I was so excited about this doh-server but found no tutorial on how to set it up. Iranian regime is closing all DoH servers. We have to create our own DoH server to fight this censorship

please do add a tutorial

Thanks

**Comment by jedisct1** [comment]
Hi!

What parts of the README file would benefit from more  verbose documentation?

DNSCrypt may be easier to setup (see https://github.com/DNSCrypt/encrypted-dns-server - there's also a docker image). And if the intent is to bypass a country's restrictions, it makes way more sense than DoH due to its instant support for anonymization.

**Comment by imanxk** [comment]
Hi,
I should first thank for the useful program and concise README file.

Because you asked, could you please elaborate on these points:
- What is the -b "Address to connect from"?
- What is -g? (Is this the outside address of my server? I have already set -H example.com)
- On the section "Example usage with nginx", should the location read as "/dns-query" instead of "/doh" ?

I appreciate providing and confirming a correct client request template like: 
         https://example.com/dns-query?name=www.yahoo.com 

[BTW: I am using it under Nginx on my domain example.com with Letsencrypt SSL, with a local upstream DNS server (Pi-hole) on 127.0.01:53, but I get http error 406]

Thanks, and Regards
Iman

**Comment by jedisct1** [comment]
`-b` is the address the DoH proxy is going to use to connect to the DNS server
`-g` is the *public* address of the DoH server.

The path can be anything; it doesn't have to be `/dns-query`. But since this is confusing, the example in the documentation was changed to `/dns-query`. Thanks!

Error 406 usually means that you tried to load the content like a regular web page using a web browser, instead of using an actual DoH client like dnscrypt-proxy.
